name: 0. IAM Configuration

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'

env:
  AWS_REGION: ${{ github.event.inputs.region }}
  GITHUB_OIDC_PROVIDER_URL: "token.actions.githubusercontent.com"
  GITHUB_OIDC_AUDIENCE: "sts.amazonaws.com"

permissions:
  id-token: write
  contents: read

jobs:
  setup-iam:
    name: Setup IAM OIDC and Roles
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Get AWS Account ID
        id: get-aws-account
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV

      - name: Create IAM OIDC Provider
        run: |
          OIDC_PROVIDER_EXISTS=$(aws iam list-open-id-connect-providers | grep $GITHUB_OIDC_PROVIDER_URL || echo "")
          
          if [ -z "$OIDC_PROVIDER_EXISTS" ]; then
            echo "Creating OIDC Provider for GitHub Actions..."
            
            # Create IAM OIDC identity provider
            aws iam create-open-id-connect-provider \
              --url https://$GITHUB_OIDC_PROVIDER_URL \
              --client-id-list $GITHUB_OIDC_AUDIENCE \
              --thumbprint-list "6938fd4d98bab03faadb97b34396831e3780aea1"
          else
            echo "OIDC Provider for GitHub Actions already exists"
          fi
          
          # Get the OIDC Provider ARN
          OIDC_PROVIDER_ARN=$(aws iam list-open-id-connect-providers | jq -r '.OpenIDConnectProviderList[] | select(.Arn | contains("'$GITHUB_OIDC_PROVIDER_URL'")) | .Arn')
          echo "OIDC Provider ARN: $OIDC_PROVIDER_ARN"
          echo "OIDC_PROVIDER_ARN=$OIDC_PROVIDER_ARN" >> $GITHUB_ENV
      
      - name: Create GitHub Actions IAM Role
        run: |
          ROLE_NAME="GitHub-Actions-Talk2Me-Role"
          ROLE_EXISTS=$(aws iam get-role --role-name $ROLE_NAME 2>&1 | grep "NoSuchEntity" || echo "exists")
          
          if [ "$ROLE_EXISTS" != "exists" ]; then
            echo "Creating IAM role for GitHub Actions..."
            
            # Write the trust policy to a file using a script approach
            echo '{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "'"$OIDC_PROVIDER_ARN"'"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                    "StringEquals": {
                      "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                    },
                    "StringLike": {
                      "token.actions.githubusercontent.com:sub": "repo:'"${{ github.repository }}"':*"
                    }
                  }
                }
              ]
            }' > trust-policy.json
            
            # Create the role
            aws iam create-role \
              --role-name $ROLE_NAME \
              --assume-role-policy-document file://trust-policy.json \
              --description "Role for GitHub Actions to deploy Talk2Me application"
          else
            echo "IAM role for GitHub Actions already exists"
          fi
          
          echo "ROLE_NAME=$ROLE_NAME" >> $GITHUB_ENV
          echo "ROLE_ARN=arn:aws:iam::$AWS_ACCOUNT_ID:role/$ROLE_NAME" >> $GITHUB_ENV
      
      - name: Create IAM Policy for Talk2Me Deployment
        run: |
          POLICY_NAME="Talk2Me-Deployment-Policy"
          POLICY_EXISTS=$(aws iam get-policy --policy-arn arn:aws:iam::$AWS_ACCOUNT_ID:policy/$POLICY_NAME 2>&1 | grep "NoSuchEntity" || echo "exists")
          
          if [ "$POLICY_EXISTS" != "exists" ]; then
            echo "Creating IAM policy for Talk2Me deployment..."
            
            # Write the policy document to a file
            echo '{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "eks:*",
                    "ec2:*",
                    "ecr:*",
                    "iam:GetRole",
                    "iam:CreateRole",
                    "iam:DeleteRole",
                    "iam:AttachRolePolicy",
                    "iam:DetachRolePolicy",
                    "iam:PutRolePolicy",
                    "iam:GetRolePolicy",
                    "iam:DeleteRolePolicy",
                    "iam:CreatePolicy",
                    "iam:ListPolicies",
                    "iam:GetPolicy",
                    "iam:ListAttachedRolePolicies",
                    "iam:PassRole",
                    "iam:CreateServiceLinkedRole",
                    "iam:TagRole",
                    "iam:GetOpenIDConnectProvider",
                    "iam:CreateOpenIDConnectProvider",
                    "iam:DeleteOpenIDConnectProvider",
                    "iam:TagOpenIDConnectProvider",
                    "iam:ListOpenIDConnectProviders",
                    "iam:ListOpenIDConnectProviderTags",
                    "route53:*",
                    "autoscaling:*",
                    "elasticloadbalancing:*",
                    "cloudformation:*",
                    "acm:*"
                  ],
                  "Resource": "*"
                }
              ]
            }' > policy.json
            
            # Create the policy
            POLICY_ARN=$(aws iam create-policy \
              --policy-name $POLICY_NAME \
              --policy-document file://policy.json \
              --query 'Policy.Arn' --output text)
            
            echo "Created policy with ARN: $POLICY_ARN"
          else
            POLICY_ARN="arn:aws:iam::$AWS_ACCOUNT_ID:policy/$POLICY_NAME"
            echo "IAM policy for Talk2Me deployment already exists"
            
            # Update the policy to include the missing permissions
            echo '{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "eks:*",
                    "ec2:*",
                    "ecr:*",
                    "iam:GetRole",
                    "iam:CreateRole",
                    "iam:DeleteRole",
                    "iam:AttachRolePolicy",
                    "iam:DetachRolePolicy",
                    "iam:PutRolePolicy",
                    "iam:GetRolePolicy",
                    "iam:DeleteRolePolicy",
                    "iam:CreatePolicy",
                    "iam:ListPolicies",
                    "iam:GetPolicy",
                    "iam:ListAttachedRolePolicies",
                    "iam:PassRole",
                    "iam:CreateServiceLinkedRole",
                    "iam:TagRole",
                    "iam:GetOpenIDConnectProvider",
                    "iam:CreateOpenIDConnectProvider",
                    "iam:DeleteOpenIDConnectProvider",
                    "iam:TagOpenIDConnectProvider",
                    "iam:ListOpenIDConnectProviders",
                    "iam:ListOpenIDConnectProviderTags",
                    "route53:*",
                    "autoscaling:*",
                    "elasticloadbalancing:*",
                    "cloudformation:*",
                    "acm:*"
                  ],
                  "Resource": "*"
                }
              ]
            }' > policy.json
            
            # Create a new version of the policy
            aws iam create-policy-version \
              --policy-arn $POLICY_ARN \
              --policy-document file://policy.json \
              --set-as-default
              
            echo "Updated policy with ARN: $POLICY_ARN"
          fi
          
          # Attach policy to role
          aws iam attach-role-policy \
            --role-name $ROLE_NAME \
            --policy-arn $POLICY_ARN
          
          echo "Attached deployment policy to role"
      
      - name: Output Configuration
        run: |
          echo "==========================================================="
          echo "AWS IAM Configuration Complete"
          echo "==========================================================="
          echo "Region: $AWS_REGION"
          echo "Account ID: $AWS_ACCOUNT_ID"
          echo "GitHub OIDC Provider ARN: $OIDC_PROVIDER_ARN"
          echo "GitHub Actions Role ARN: $ROLE_ARN"
          echo ""
          echo "Add the following secrets to your GitHub repository:"
          echo "AWS_ROLE_ARN: $ROLE_ARN"
          echo "============================================================"
          echo ""
          echo "IMPORTANT: You will also need to add your DEEPSEEK_API_KEY as a GitHub Secret."