name: 1. EKS Cluster Setup
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      cluster_name:
        description: 'EKS Cluster Name'
        required: true
        default: 'talk2me-cluster'
      node_group_size:
        description: 'Node Group Size (min,desired,max)'
        required: true
        default: '2,3,4'
      node_instance_type:
        description: 'EC2 Instance Type for Nodes'
        required: true
        default: 't3.medium'
      kubernetes_version:
        description: 'Kubernetes Version'
        required: true
        default: '1.28'
env:
  AWS_REGION: ${{ github.event.inputs.region }}
  CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}

permissions:
  id-token: write
  contents: read

jobs:
  eks-setup:
    name: Create EKS Cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
        uses: actions/checkout@v3
        
    - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Install eksctl
        run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        eksctl version
    
    - name: Create EKS cluster
        run: |
        # Parse node group size parameters
        IFS=',' read -ra SIZES <<< "${{ github.event.inputs.node_group_size }}"
        MIN_SIZE=${SIZES[0]}
        DESIRED_SIZE=${SIZES[1]}
        MAX_SIZE=${SIZES[2]}
        
        eksctl create cluster \
            --name $CLUSTER_NAME \
            --region $AWS_REGION \
            --version ${{ github.event.inputs.kubernetes_version }} \
            --nodegroup-name standard-nodes \
            --node-type ${{ github.event.inputs.node_instance_type }} \
            --nodes-min $MIN_SIZE \
            --nodes $DESIRED_SIZE \
            --nodes-max $MAX_SIZE \
            --with-oidc \
            --managed \
            --asg-access
    
    - name: Configure Load Balancer Controller
      run: |
        # Update kubeconfig
        aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
        
        # Install AWS Load Balancer Controller
        helm repo add eks https://aws.github.io/eks-charts
        helm repo update
        
        # Create IAM service account
        eksctl create iamserviceaccount \
            --cluster=$CLUSTER_NAME \
            --namespace=kube-system \
            --name=aws-load-balancer-controller \
            --role-name AmazonEKSLoadBalancerControllerRole \
            --attach-policy-arn=arn:aws:iam::aws:policy/AWSLoadBalancerControllerIAMPolicy \
            --approve
        
        # Install Load Balancer Controller
        helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
            -n kube-system \
            --set clusterName=$CLUSTER_NAME \
            --set serviceAccount.create=false \
            --set serviceAccount.name=aws-load-balancer-controller
    
    - name: Create Application Namespace
      run: |
        kubectl create namespace talk2me || true
        
    - name: Output Cluster Details
      run: |
        echo "EKS Cluster $CLUSTER_NAME created successfully"
        echo "Region: $AWS_REGION"
        echo "Kubernetes Version: ${{ github.event.inputs.kubernetes_version }}"
        echo "Node Group Size: ${{ github.event.inputs.node_group_size }}"
        echo "Node Instance Type: ${{ github.event.inputs.node_instance_type }}"